In [58]:
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above
import numpy as np
a = np.zeros(5)
print(a)
print(a.dtype)
print(a.itemsize)
print(a.shape)

[0. 0. 0. 0. 0.]
float64
8
(5,)


In [59]:
# create a numpy array of ones of shape (5,4)
a = np.random.randint(10,30,20)
b = a.reshape(5,4)
print(b)
print(b.shape)

[[17 27 12 16]
 [16 27 21 27]
 [14 10 13 19]
 [28 19 21 21]
 [21 17 28 14]]
(5, 4)


In [60]:
# create a matrix of shape 4,5 with numbers from 1-20
import numpy as np
a1 = np.random.randint(1,20,20)
print(a1)
a2 = a1.reshape(4,5)
print(a2)


[ 2 11  8 19 12 13 11 11 16 12 14 19 19 18  9  2  2 19 19 14]
[[ 2 11  8 19 12]
 [13 11 11 16 12]
 [14 19 19 18  9]
 [ 2  2 19 19 14]]


In [61]:
# multiply all elements of above array by 10
print(a2*10)

[[ 20 110  80 190 120]
 [130 110 110 160 120]
 [140 190 190 180  90]
 [ 20  20 190 190 140]]


In [80]:
# print odd elements from array
a3 = [i for i in a1 if i%2 ==1]
print(a3)


[11, 19, 13, 11, 11, 19, 19, 9, 19, 19]


In [81]:
# replace all even elements by their negative
even_no = (a1%2 ==0)
a1[even_no]= -1
print(a1)

[-1 11 -1 19 -1 13 11 11 -1 -1 -1 19 19 -1  9 -1 -1 19 19 -1]


In [63]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
a4 = np.linspace(1,16,16)
M1 = a4.reshape(4,4)
print(M1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [65]:
# create a transpose of above matrix call it M2
M2 = M1.transpose()
print(M2)


[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [66]:
# find sum of above matrix M3 = (M1 + M2)
M3 = M1+M2
print(M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [67]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.transpose()
print(MT1)
print(M3==MT1)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [68]:
# find diffrence of M4 = (M1 - M2)
M4 = (M1-M2)
print(M4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [69]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = M4.transpose()
print(MT2)
print(M4==-MT2)

[[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [70]:
# create a matrix (3x4) R1 of random numbers between 10-40
a5 = np.random.randint(10,40,12)
r1 = a5.reshape(3,4)
print(r1)


[[20 35 13 26]
 [29 17 37 18]
 [13 37 14 29]]


In [71]:
# find min and max column wise
minimum = r1.min(axis=0)
print(minimum)
maximum = r1.max(axis=0)
print(maximum)

[13 17 13 18]
[29 37 37 29]


In [74]:
# replace the last column with sum of all the columns
print(r1)
c0 = r1.sum(axis=0)
print(c0)
r1[0,3] = c0[0]
r1[1,3] = c0[1]
r1[2,3] = c0[2]
print(r1)

[[ 20  35  13  62]
 [ 29  17  37 106]
 [ 13  37  14  87]]
[ 62  89  64 255]
[[20 35 13 62]
 [29 17 37 89]
 [13 37 14 64]]


In [84]:
# create a matrix (3x4) R1 of random numbers between 10-40
a6 = np.random.randint(10,40,12)
r1 = a6.reshape(3,4)
print(r1)
print(a6)

[[39 30 12 25]
 [22 10 16 10]
 [34 14 12 27]]
[39 30 12 25 22 10 16 10 34 14 12 27]


In [96]:
# replace all even elements with nan in R1
even_no = (a6%2==0)
a6[even_no] = -1

print(a6)

[39 -1 -1 25 -1 -1 -1 -1 -1 -1 -1 27]


In [ ]:
# count number of nan in R1

# check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

In [99]:
# 1. 
a = [1,2,3]
print(a[::-1][::2])
# Ys Here > y y yyyyy
# Ns Here >n

# 2. 
a  = [1,2,3]
print( list(  map(lambda x: x*x, a)   )  )
# Ys Here >y yy
# Ns Here >nn

# 3. 
print(print)
print(print())
# Ys Here >
# Ns Here >nnnn

[3, 1]
[1, 4, 9]
<built-in function print>

None
