## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [4]:
# create a numpy array of 5 zeros.
import numpy as np

arr = np.zeros(5)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.itemsize)

[0. 0. 0. 0. 0.]
float64
(5,)
8


In [7]:
# create a numpy array of ones of shape (5,4)
arr_ones = np.ones((5,4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [44]:
# create a matrix of shape 4,5 with numbers from 1-20
matrix = (np.arange(1,21)).reshape(4,5)
print(matrix)

# multiply all elements of above array by 10
print()
print("After multiply all elements of above array by 10 are :")
mul_matrix = matrix * 10
print(mul_matrix)


# print odd elements from array
print()
oddd_matrix = np.where(matrix % 2 == 1)
rows = oddd_matrix[0]
columns = oddd_matrix[1]
print("odd elements from array are:")
for x, y in zip(rows,columns):
    print(matrix[x][y], end=" ")

    
# - replace all even elements by their negative
print("\n")
even_matrix = np.where(matrix % 2 == 0, -1 * matrix, matrix)
print("After replace all even elements by their negative are:")
print(even_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

After multiply all elements of above array by 10 are :
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]

odd elements from array are:
1 3 5 7 9 11 13 15 17 19 

After replace all even elements by their negative are:
[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [70]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
print("linearly spaced matrix M1 of size 4x4 having values in range 1-16 is: ")
M1 = np.linspace(1,16,16, dtype="int8")
M1.resize(4,4)
print(M1)

# create a transpose of above matrix call it M2
print("\n")
M2 = M1.T
print("transpose of above matrix, M2 is:\n",M2)


# find sum of above matrix M3 = (M1 + M2)
print("\n")
print("Sum of above two matrix M3 is")
M3 = M1 + M2
print(M3)

# Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.T
print("\n To Check if M3 == MT1")
# print(M3 == MT1)
if (M3==MT1).all():
    print("Yes, M3 and M1.T are similar.")


# find diffrence of M4 = (M1 - M2)
print("\nTo check diffrence of M4 = (M1 - M2)")
M4 = M1 - M2
print("M4 matrix is :\n",M4)

# - Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
print("\nQue: To find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2")
MT2 = M4.T

if (M4 == MT2).all():
    print("M4 and MT2 are similar")
elif (M4 == -MT2).all():
    print("M4 and -MT2 are similar")
print("\n")    

linearly spaced matrix M1 of size 4x4 having values in range 1-16 is: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


transpose of above matrix, M2 is:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


Sum of above two matrix M3 is
[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

 To Check if M3 == MT1
Yes, M3 and M1.T are similar.

To check diffrence of M4 = (M1 - M2)
M4 matrix is :
 [[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]

Que: To find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
M4 and -MT2 are similar




In [94]:
# - create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40, 12)
R1.resize(3,4)
print("Que: create a matrix (3x4) R1 of random numbers between 10-40.")
print("R1 matrix is \n",R1)


# - find min and max column wise
min_col = R1.min(axis=0)
max_col = R1.max(axis=0)
print("\nmin value column wise are \n",min_col)
print("\nmax value column wise are \n",max_col)


# - replace the last column with sum of all the columns
R1[:,-1] = R1.sum(axis=1)
print("\nAfter replacing the last column with sum of all the columns are:")
print(R1)

Que: create a matrix (3x4) R1 of random numbers between 10-40.
R1 matrix is 
 [[20 21 37 13]
 [37 11 16 31]
 [11 22 31 38]]

min value column wise are 
 [11 11 16 13]

max value column wise are 
 [37 22 37 38]

After replacing the last column with sum of all the columns are:
[[ 20  21  37  91]
 [ 37  11  16  95]
 [ 11  22  31 102]]


In [126]:
# - create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,12)
R1.resize(3,4)
print("matrix (3x4) R1 of random numbers between 10-40 is: ")
print(R1)


# - replace all even elements with nan in R1
R1 = np.where(R1%2 == 0, np.nan, R1)
print("\n Replaced all even elements with nan in R1 and matrix is:")
print(R1)


# - count number of nan in R1
i = 0
nan_cnt = np.where(R1 * 0 != 0)
print("\nnumber of nan in R1 is : ", len(nan_cnt[0]))



matrix (3x4) R1 of random numbers between 10-40 is: 
[[11 16 34 13]
 [13 31 16 39]
 [37 28 20 33]]

 Replaced all even elements with nan in R1 and matrix is:
[[11. nan nan 13.]
 [13. 31. nan 39.]
 [37. nan nan 33.]]

number of nan in R1 is :  5
