In [6]:
import numpy as np

In [7]:
print(np)
# numpy arrays are homogeneous

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


In [8]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [17]:
a = [1,2,3]
d = np.array(a)
print(d,a)
print(type(d), type(a))

print(d[0])
print(d[-1])

print()
for num in d:
    print(num)

[1 2 3] [1, 2, 3]
<class 'numpy.ndarray'> <class 'list'>
1
3

1
2
3


In [22]:
d = np.array([11,22,33])

print(d.dtype)
print(d.size)
print(d.shape)

int32
3
(3,)


In [33]:
d = np.array([[1100000000000000000,22,33]], )

print(d.dtype)
print(d.size)
print(d.shape)
print(d.itemsize)

int64
3
(1, 3)
8


In [34]:
d = np.array([[110,22,33]], dtype = "int8")

print(d.dtype)
print(d.size)
print(d.shape)
print(d.itemsize)

int8
3
(1, 3)
1


In [27]:
d = np.array([[11,22,33],[4.5,"55",66]])

print(d)
print(d.dtype) # < little endian 32bits is size of each char
print(d.size)
print(d.shape)
print(d.itemsize)

[['11' '22' '33']
 ['4.5' '55' '66']]
<U32
6
(2, 3)
128


In [38]:
# utility functions
r = np.arange(1,10,2) # actually generates numbers
print(r)
print(type(r))

#[1,2,3]
#range(1,4) # generator

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [62]:
r = np.random.randint(1, 10, 4)
print(r, type(r))

r = np.random.randint(1, 10)
print(r, type(r))

[7 5 2 6] <class 'numpy.ndarray'>
4 <class 'int'>


In [69]:
r = np.random.randint(1,100, 20)
r1 = r.reshape(4,5)
print(r, r.shape)
print(r1, r1.shape)
print(r1.reshape(2,10))
print(r1.reshape(2,3))

[27 23 26 57  5 22 21 67 87 57 26 29 27 62 57 48 25 29 28 86] (20,)
[[27 23 26 57  5]
 [22 21 67 87 57]
 [26 29 27 62 57]
 [48 25 29 28 86]] (4, 5)
[[27 23 26 57  5 22 21 67 87 57]
 [26 29 27 62 57 48 25 29 28 86]]


ValueError: cannot reshape array of size 20 into shape (2,3)

In [74]:
r = np.random.randint(1,100, 20)
print(r)
r.resize(4,5)
print(r, r.shape)
r.resize(10,5)
print(r)
r.resize(2,5)
print(r)

[17 68  6  5 93 69 92 29 97 58 74 74 84 61  7  8 90  8 32 52]
[[17 68  6  5 93]
 [69 92 29 97 58]
 [74 74 84 61  7]
 [ 8 90  8 32 52]] (4, 5)
[[17 68  6  5 93]
 [69 92 29 97 58]
 [74 74 84 61  7]
 [ 8 90  8 32 52]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
[[17 68  6  5 93]
 [69 92 29 97 58]]


In [75]:
r1 = np.arange(1,11)
r1.resize(2,5)
print(r1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [87]:
# broadcasting
a  = np.array([10,20])
print(a)
print(r1)

print()
print(r1*10)
print(r1-5)
print(r1)


print(r1+a)

[10 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[[-4 -3 -2 -1  0]
 [ 1  2  3  4  5]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [86]:
r2 = r1-5
r3 = np.array([10,20,30,40,50])
print(r1)
print(r2)
print(r3)

print()
print(r1-r2)

print()
print(r1*r2)

print()
print(r1*r3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[-4 -3 -2 -1  0]
 [ 1  2  3  4  5]]
[10 20 30 40 50]

[[5 5 5 5 5]
 [5 5 5 5 5]]

[[-4 -6 -6 -4  0]
 [ 6 14 24 36 50]]

[[ 10  40  90 160 250]
 [ 60 140 240 360 500]]


In [94]:
print(r1)

print()
print(r1.sum())
print(r1.min())
print(r1.max())
print(r1.mean())

print()
print("axis 1")
print(r1.sum(axis=1))
print(r1.min(axis=1))

print()
print("axis 0")
print(r1.sum(axis=0))
print(r1.min(axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

55
1
10
5.5

axis 1
[15 40]
[1 6]

axis 0
[ 7  9 11 13 15]
[1 2 3 4 5]


In [96]:
r = np.random.randint(1,100, 30)
r1 = r.reshape(3,2,5)
print(r1)

[[[34 44 72 61 38]
  [26  8 56 97 15]]

 [[67 58 73  9 92]
  [76 86 61  3 49]]

 [[68 32  3 83 38]
  [35 33 19 44 37]]]


In [107]:
print(np.arange(10,20))
print(np.linspace(40,50,10)) # AP- progression
print(np.linspace(40,50,10, dtype="int8")) # AP- progression

[10 11 12 13 14 15 16 17 18 19]
[40.         41.11111111 42.22222222 43.33333333 44.44444444 45.55555556
 46.66666667 47.77777778 48.88888889 50.        ]
[40 41 42 43 44 45 46 47 48 50]


In [111]:
print(np.zeros(10))
print(np.zeros((10,2)))

print(np.ones(10))
print(np.ones((10,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
1 2 3 
4 5 6

1 2 3 4 5 6

1 4 2 5 3 6