In [1]:
import numpy as np

In [9]:
num = np.zeros(5)
print(num)
print(num.dtype)
print(num.itemsize)
print(num.shape)

[0. 0. 0. 0. 0.]
float64
8
(5,)


In [17]:
num=np.ones(20)
num1=num.reshape(5,4)
print(num1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
mat=np.arange(1,21)
mat1=mat.reshape(4,5)
print(mat1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [24]:
print(mat1*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [34]:
is_even=(mat1%2==0)
print("The odd values are \n", mat1[~is_even])

The odd values are 
 [ 1  3  5  7  9 11 13 15 17 19]


In [40]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [44]:
import math
neg=(mat1[is_even])
print(np.negative(neg))

[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


In [55]:
val=np.arange(1,17)
M1=val.reshape(4,4)
print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [56]:
M2=M1.transpose()
print(M2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [58]:
M3=sum(M1,M2)
print(M3)

[[29 37 45 53]
 [30 38 46 54]
 [31 39 47 55]
 [32 40 48 56]]


In [67]:
MT1=M3.transpose()
print(MT1)

[[29 30 31 32]
 [37 38 39 40]
 [45 46 47 48]
 [53 54 55 56]]


In [65]:
M=(MT1==M3)
print(M.all())

False


In [74]:
M4=M1-M2
print("The differnce of the matrices M1 and M2 \n",M4)

The differnce of the matrices M1 and M2 
 [[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [81]:
MT2=M4.transpose()
print(MT2)

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]


In [83]:
MM=M4==MT2
print(MM.all())

MN=M4==(-MT2)
print(MN.all())

False
True


In [96]:
R=np.random.randint(10,40,12)
R1=R.reshape(3,4)
print(R1)

[[16 22 10 24]
 [37 13 28 13]
 [31 13 22 16]]


In [102]:
R2=R1.min(axis=0)
print(R2)
R3=R1.max(axis=0)
print(R3)

[16 13 10 13]
[37 22 28 24]


In [156]:
R1=np.random.randint(10,40,12)
R2=R1.reshape(3,4)
print(R2)
print()
is_even=(R2%2==0)
eve=(R2[is_even==1])


[[30 10 19 10]
 [26 27 11 23]
 [15 23 27 34]]

